version: '3'
services:
    api:
        build: ./Backend/Api/
        ports:
            - 8000:8000
        networks: 
            - default
    db:
        image: mysql:latest
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'qr_boxes'
          # So you don't have to use root, but you can if you like
          MYSQL_USER: 'qr_boxes'
          # You can use whatever password you like
          MYSQL_PASSWORD: '9PszVpg%QipJ4*p@zS6$gph&g%Qi'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'WXXJ#v2#CwAYJ%3U7@pT'
        ports:
          # <Port exposed> : < MySQL Port running inside container>
          - '3306:3306'
        expose:
          # Opens port 3306 on the container
          - '3306'
          # Where our data will be persisted
        volumes:
          - db_volume:/var/lib/mysql
        networks: 
          - default

volumes:
    db_volume:
networks: 
    default: