version: '3'
services:
    api:
        build: ./Backend/Api/
        ports:
            - 8000:8000
        networks: 
            - default
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 9PszVpg%QipJ4*p@zS6$gph&g%Qi
        ports:
            - '3306:3306'
            # - '3306'
        volumes:
            - db_volume:/var/lib/mysql    
        networks: 
            - default  
volumes:
    db_volume:
networks: 
    default: